---
# This workflow runs the repo's CI tests.
name: CI

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false

    defaults:
      run:
        shell: bash -elo pipefail {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          cache-dependency-glob: uv.lock
          enable-cache: true

      - name: Install environment
        run: uv sync

      - name: Cache pre-commit
        uses: actions/cache@v6
        with:
          path: ~/.cache/prek/
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit checks
        run: uv run prek run --all-files
        env:
          SKIP: no-commit-to-branch

      - name: Test
        run: |
          uv pip check
          ipython -c "import osmnx"
